city/urls.py
from django.contrib import admin
from django.urls import path
from .views import CityPageView,CityDeltailView,CityEditView,CityDeleteView


app_name='city'
urlpatterns = [
    path('city_home/', CityPageView.as_view(),name='city_home'),
    path('city_detail/<int:id>/',CityDeltailView.as_view(), name='city_detail'),
    path('edit_city_details/<int:id>/',CityEditView.as_view(), name='edit_city_details'),
    path('delete_city/<int:id>/', CityDeleteView.as_view(), name='delete_city'),


]

country/urls.py
from django.contrib import admin
from django.urls import path
from .views import HomePageView,DeltailView,EditView,DeleteView


app_name='country'
urlpatterns = [
    path('country_home/', HomePageView.as_view(),name='country_home'),
    path('detail/<int:id>/',DeltailView.as_view(), name='detail'),
    path('edit_detail/<int:id>/',EditView.as_view(), name='edit_detail'),
    path('delete_country/<int:id>/', DeleteView.as_view(), name='delete_country')
]

globe/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import HomeView
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',HomeView,name='home'),
    path(r'country/',include('country.urls'), name='country'),
    path(r'state/',include('state.urls'), name='state'),
    path(r'city/',include('city.urls'), name='city'),
    path(r'users/',include('users.urls'), name='users'),
    path(r'backendapp/',include('backendApp.urls'), name='backendapp'),
   
]

country/models.py
from django.db import models
from django.contrib.auth.models import User


class Country(models.Model):
    name = models.CharField(unique=True,max_length=100,)
    code = models.CharField(max_length=20)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(blank=True,null=True)
    is_deleted = models.BooleanField(default=False)
    created_by = models.ForeignKey(User,related_name='created_by',on_delete=models.CASCADE)
    updated_by = models.ForeignKey(User,related_name='updated_by',on_delete=models.CASCADE,blank=True,null=True)

country/views.py
from django.shortcuts import render,HttpResponseRedirect,redirect
from django.views import View
from .models import Country
from django.contrib import messages
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required


def class_view_decorator(function_decorator):
    def simple_decorator(View):
        View.dispatch = method_decorator(function_decorator)(View.dispatch)
        return View

    return simple_decorator


@class_view_decorator(login_required)    
class HomePageView(View):
    def get(self,request):
        countries = Country.objects.filter(is_deleted=False)
        query = self.request.GET.get('search')
        print(query)
        if query:
             countries = Country.objects.filter(name__icontains=query,is_deleted=False)
        else:
             countries = Country.objects.filter(is_deleted=False)
        return render(request,'country/home.html',locals())
        
    def post(self,request):
        country_name = request.POST.get('name')
        print(country_name)
        country_code = request.POST.get('code')
        created_by=request.user
        print(created_by)
        data = Country(name=country_name,code=country_code,created_by=created_by)
        print(data,"sdksdksdsldls")
        try:
            if country_name and country_code:
                    data.save()
                    messages.success(request, 'Created!!')
            else:
                messages.warning(request, 'enter name and code!!!')
        except:
             messages.warning(request, 'Alreday exits')
            
        return redirect('country:country_home')


@class_view_decorator(login_required)
class DeltailView(View):
    def get(self,request,id):
        Country_detail = Country.objects.get(pk=id)
        print(Country_detail,"hi")
        return render(request,'country/details.html',locals())


@class_view_decorator(login_required)        
class EditView(View):
    def get(self,request,id):
        Country_detail = Country.objects.get(pk=id)
        print(Country_detail,"hi")
        return render(request,'country/edit.html',locals())
    def post(self,request,id):
        country_name = request.POST.get('name')
        country_code = request.POST.get('code')
        Country_detail = Country.objects.get(pk=id)
        Country_detail.name = country_name
        Country_detail.code = country_code
        Country_detail.save()
        return redirect('country:country_home')

@class_view_decorator(login_required)
class DeleteView(View):
    def get(self,request,id):
        Country_detail = Country.objects.get(pk=id)
        print(Country_detail,"hi")
        Country_detail.is_deleted = True
        Country_detail.save()
        messages.warning(request, 'Successfully Deleted')
        return redirect('country:country_home')

        

templates/country/create.html
{% extends 'base.html' %}

{% block content %}
    <div class="row">
        <div class="col-md-6">
            <h4 class="text-center alert alert-primary">Country detail Update Here</h4>
            <form action="" method="post">
                {% csrf_token %}
                <label for="name">Name</label><br>
                <input type="text" id="name" name="name" value="{{ Country_detail.name }}"><br>
                <label for="code">Code</label><br>
                <input type="text" id="code" name="code" value="{{ Country_detail.code }}"><br><br>
                <label for="created_at">Created_at</label><br>
                <input type="datetime" id="created_at" name="created_at" value="{{ Country_detail.created_at|date:'Y-m-d' }}"><br><br>
                <label for="updated_at">Updated_at</label><br>
                <input type="datetime" id="updated_at" name="updated_at" value="{{ Country_detail.updated_at|date:'Y-m-d' }}"><br><br>
                <label for="is_deleted">Is_deleted</label><br>
                <input type="text" id="is_deleted" name="is_deleted" value="{{ Country_detail.is_deleted }}"><br><br>
                <input type="submit" value="Submit">
              </form> 
              
        </div>
    </div>
{% endblock %}

templates/country/details.html
{% extends "base.html" %}

{% block content %}
<div class="row">
    <div class="col-sm-8">
        <h3 class="text-center alert-primary alert">Filter Record Like This</h3>

        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">#ID.</th>
                    <th scope="col">Name</th>
                    <th scope="col">CODE</th>
                    <th scope="col">CREATED_AT</th>
                    <th scope="col">UPDATED_AT</th>

                </tr>
            </thead>
            <tbody>
               
                <tr>
                    <td>{{ Country_detail.id }}</td>
                    <td>{{ Country_detail.name }}</td>
                    <td>{{ Country_detail.code }}</td>
                    <td>{{ Country_detail.created_at }}</td>
                    <td>{{ Country_detail.updated_at }}</td>
                </tr>
               
            </tbody>
        </table>

    </div>
</div>
{% endblock content %}

templates/country/edit.html
{% extends 'base.html' %}

{% block content %}
    <div class="row">
        <div class="col-md-6">
            <h4 class="text-center alert alert-primary">Country detail Update Here</h4>
            <form action="" method="post">
                {% csrf_token %}
                <label for="name">Name</label><br>
                <input type="text" id="name" name="name" value="{{ Country_detail.name }}"><br>
                <label for="code">Code</label><br>
                <input type="text" id="code" name="code" value="{{ Country_detail.code }}"><br><br>
                
                <input type="submit" value="Submit">
              </form> 
              
        </div>
    </div>
{% endblock %}

templates/country/home.html
{% extends "base.html" %} 

{% block content %}
    <div class="row">
        <div class="col-8">
            <h4 class="text-center alert alert-primary">Add new Country</h4>
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-success alert-dismissible fade show" role="alert">
                        {{ message }}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                {% endfor %}
            {% endif %}
            <form action="" method="post">
                {% csrf_token %}
                <label for="name">Name</label><br>
                <input type="text" id="name" name="name" value="{{ data.name }}" required><br>
                <label for="code">Code</label><br>
                <input type="text" id="code" name="code" value="{{ data.code }}" required><br><br>
                <input type="submit" value="Submit">
              </form> 
             
              
        </div>
         <div class="col-4">
            
         </div>
        </div>
        <div class="col-12">
            <h3 class="text-center alert-primary alert">Filter Record Like This
                <form class="add_your_class"  action="{% url 'country:country_home' %}" >
                    <input  id="search" name="search"type="search" name="search"> 
                    <button  type="submit"> Search </button>
                </form>
            </h3>
            
                  <table class="table table-hover">
                      <thead>
                          <tr>
                            <th scope="col">#ID.</th>
                            <th scope="col">Name</th>
                            <th scope="col">CODE</th>
                            <th scope="col">CREATED_AT</th>
                           
                          </tr>
                      </thead>
                      <tbody>
                       
                        {% for country in countries %}
                          <tr>
                              
                              <td>{{ country.id }}</td>
                              <td>{{ country.name }}</td>
                              <td>{{ country.code }}</td>
                              <td>{{ country.created_at }}</td>
                              <td>  <a href="{% url 'country:detail' country.id %}" class="btn btn-sm btn-info">Details</a></td>
                              <td>  <a href="{% url 'country:edit_detail' country.id %}" class="btn btn-sm btn-info">Edit</a></td>
                              <td>  <a href="{% url 'country:delete_country' country.id %}" class="btn btn-sm btn-info">Delete</a></td>


                          </tr>
                {% endfor %}
                      </tbody>

                  </table>
           
          
        </div>
    </div>
{% endblock content %}

templates/country/list.html
{% extends "base.html" %} 

{% block content %}
    <div class="row">
        <div class="col-8">
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-success alert-dismissible fade show" role="alert">
                        {{ message }}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                {% endfor %}
            {% endif %}
              
        </div>
         <div class="col-4">
            <form class="add_your_class"  action="" >
                <input  id="search" name="search"type="search" name="search"> 
                <button  type="submit"> Search </button>
            </form>
         </div>
        </div>
        <div class="col-12">
            <h3 class="text-center alert-primary alert">Filter Record Like This</h3>
            {% if countries %}
                  <table class="table table-hover">
                      <thead>
                          <tr>
                            <th scope="col">#ID.</th>
                            <th scope="col">Name</th>
                            <th scope="col">CODE</th>
                            <th scope="col">CREATED_AT</th>
                           
                          </tr>
                      </thead>
                      <tbody>
                        {% for country in countries %}
                          <tr>
                              <td>{{ country.id }}</td>
                              <td>{{ country.name }}</td>
                              <td>{{ country.code }}</td>
                              <td>{{ country.created_at }}</td>
                              <td>  <a href="{% url 'detail' country.id %}" class="btn btn-sm btn-info">Details</a></td>
                              <td>  <a href="{% url 'edit_detail' country.id %}" class="btn btn-sm btn-info">Edit</a></td>

                          </tr>
                {% endfor %}
                      </tbody>

                  </table>
            {% else %}
                <h4 class="alert alert-danger text-center">No Records</h4>

            {% endif %}
        </div>
    </div>
{% endblock content %}

templates/country/search.html
{% extends 'base.html' %}

{% block content %}
<h1>Search Results</h1>
<form class="add_your_class"  action="" >
    <input  id="search" name="search"type="search" name="search"> 
    <button  type="submit"> Search </button>
</form>
<div class="row">
    <div class="col-sm-8">
        <h3 class="text-center alert-primary alert">Filter Record Like This</h3>

        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">#ID.</th>
                    <th scope="col">Name</th>
                    <th scope="col">CODE</th>
                    <th scope="col">CREATED_AT</th>
                    <th scope="col">UPDATED_AT</th>
                    
                    

                </tr>
            </thead>
            <tbody>
               
                <tr>
                    {% for data in result%}
                    <td>{{ data.id }}</td>
                    <td>{{ data.name }}</td>
                    <td>{{ data.code }}</td>
                    <td>{{ data.created_at }}</td>
                    <td>{{ data.updated_at }}</td>
                    {% endfor %}
                </tr>
               
            </tbody>
        </table>

    </div>
</div>
  
{% endblock %}