city/urls.py
from django.contrib import admin
from django.urls import path
from .views import CityPageView,CityDeltailView,CityEditView,CityDeleteView


app_name='city'
urlpatterns = [
    path('city_home/', CityPageView.as_view(),name='city_home'),
    path('city_detail/<int:id>/',CityDeltailView.as_view(), name='city_detail'),
    path('edit_city_details/<int:id>/',CityEditView.as_view(), name='edit_city_details'),
    path('delete_city/<int:id>/', CityDeleteView.as_view(), name='delete_city'),


]

globe/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import HomeView
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',HomeView,name='home'),
    path(r'country/',include('country.urls'), name='country'),
    path(r'state/',include('state.urls'), name='state'),
    path(r'city/',include('city.urls'), name='city'),
    path(r'users/',include('users.urls'), name='users'),
    path(r'backendapp/',include('backendApp.urls'), name='backendapp'),
   
]

state/urls.py
from django.contrib import admin
from django.urls import path
from .views import StatePageView,StateDeleteView,StateEditView,StateDeltailView

app_name='state'

urlpatterns = [
    path('state_home/', StatePageView.as_view(),name='state_home'),
    path('delete_state/<int:id>/', StateDeleteView.as_view(), name='delete_state'),
    path('edit_state_details/<int:id>/',StateEditView.as_view(), name='edit_state_details'),
    path('state_detail/<int:id>/',StateDeltailView.as_view(), name='state_detail'),
]
# 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

state/models.py
from django.db import models
from country.models import Country
from django.contrib.auth.models import User


class State(models.Model):
    country=models.ForeignKey(Country,on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    code=models.CharField(max_length=20,null=False,blank=False)
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(blank=True, null=True)
    is_deleted=models.BooleanField(default=False)
    created_by = models.ForeignKey(User,related_name='state_created_by',on_delete=models.CASCADE)
    updated_by = models.ForeignKey(User,related_name='state_updated_by',on_delete=models.CASCADE,blank=True,null=True)

state/views.py
from django.shortcuts import render,HttpResponseRedirect,redirect
from django.views import View
from .models import State
from country.models import Country
from django.contrib import messages
from django.shortcuts import get_object_or_404
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required



def class_view_decorator(function_decorator):
    """Convert a function based decorator into a class based decorator usable
    on class based Views.

    Can't subclass the `View` as it breaks inheritance (super in particular),
    so we monkey-patch instead.
    """

    def simple_decorator(View):
        View.dispatch = method_decorator(function_decorator)(View.dispatch)
        return View

    return simple_decorator
    
@class_view_decorator(login_required)  
class StatePageView(View):
    def get(self,request):
        query = self.request.GET.get('search')
        country_serach = self.request.GET.get('country_search')
        print(country_serach,"fjkjnfgn")
      
        if query:
             states = State.objects.filter(name__icontains=query,is_deleted=False)
        elif country_serach: 
            states = State.objects.filter(country__id__icontains=country_serach,is_deleted=False)
            print(states)
         
        else:
            states = State.objects.filter(is_deleted=False)
        countries=Country.objects.filter(is_deleted=False)
        
        return render(request,'state/home.html',locals())
    def post(self,request):
        state_name = request.POST.get('name')
        state_code = request.POST.get('code')
        selected_item = (request.POST.get('item_id'))
        country_name  = Country.objects.get(id=selected_item)
        data=State(name=state_name,code=state_code,country=country_name)
        print(data,"get")
        try:
            if state_name and  state_code and country_name:
                data.save()
                messages.success(request, 'Created!!')
            else:
                messages.warning(request, 'enter name ,code and country name!!!')

        except:
             messages.warning(request, 'Alreday exits')
        return redirect('state:state_home')

@class_view_decorator(login_required)          
class StateDeleteView(View):
    def get(self,request,id):
        state_detail = State.objects.get(pk=id)
        print(state_detail,"hi")
        state_detail.is_deleted=True
        state_detail.save()
        messages.warning(request, 'Successfully Deleted')
        return HttpResponseRedirect('/state/state_home/')

@class_view_decorator(login_required)          
class StateEditView(View):
    def get(self,request,id):
        state_detail = State.objects.get(pk=id)
        print(state_detail,"hi")
        return render(request,'state/edit.html',{'state_detail':state_detail})
    def post(self,request,id):
        state_name = request.POST.get('name')
        state_code = request.POST.get('code')

        state_detail = State.objects.get(pk=id)
        
        state_detail.name = state_name
        state_detail.code = state_code
        state_detail.save()
        return redirect('state:state_home')
        
@class_view_decorator(login_required)          
class StateDeltailView(View):
    def get(self,request,id):
        state_detail = State.objects.get(pk=id)
        print(state_detail,"hi")
        return render(request,'state/details.html',{'state_detail':state_detail})

templates/state/details.html
{% extends "base.html" %}

{% block content %}
<div class="row">
    <div class="col-sm-8">
        <h3 class="text-center alert-primary alert">Filter Record Like This</h3>

        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">#ID.</th>
                    <th scope="col">COUNTRY</th>
                    <th scope="col">Name</th>
                    <th scope="col">CODE</th>
                    <th scope="col">CREATED_AT</th>
                    <th scope="col">UPDATED_AT</th>

                </tr>
            </thead>
            <tbody>
               
                <tr>
                    <td>{{ state_detail.id }}</td>
                    <td>{{ state_detail.country.name }}</td>
                    <td>{{ state_detail.name }}</td>
                    <td>{{ state_detail.code }}</td>
                    <td>{{ state_detail.created_at }}</td>
                    <td>{{ state_detail.updated_at }}</td>
                </tr>
               
            </tbody>
        </table>

    </div>
</div>
{% endblock content %}

templates/state/edit.html
{% extends 'base.html' %}

{% block content %}
    <div class="row">
        <div class="col-md-6">
            <h4 class="text-center alert alert-primary">Country detail Update Here</h4>
            <form action="" method="post">
                {% csrf_token %}
                <label for="name">Name</label><br>
                <input type="text" id="name" name="name" value="{{ state_detail.name }}"><br>
                <label for="code">Code</label><br>
                <input type="text" id="code" name="code" value="{{ state_detail.code }}"><br><br>
                <input type="submit" value="Submit">
              </form> 
        </div>
    </div>
{% endblock %}

templates/state/home.html
{% extends "base.html" %} 

{% block content %}
    <div class="row">
        <div class="col-8">
            <h4 class="text-center alert alert-primary">Add new state</h4>
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-success alert-dismissible fade show" role="alert">
                        {{ message }}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                {% endfor %}
            {% endif %}
            <form action="" method="post">
                {% csrf_token %}
                <label for="name">Name</label><br>
                <input type="text" id="name" name="name" value="{{ states.name }}" required><br>
                <label for="code">Code</label><br>
                <input type="text" id="code" name="code" value="{{ states.code }}" required><br><br>
               
                <!-- <input type="text" id="item_id" name="item_id" value="{{ data.country }}"><br><br> -->
                <select name="item_id"  id="item_id">
                    {% for entry in countries %}
                        <option value="{{ entry.id }}">{{ entry.name }}</option>
                    {% endfor %}
                </select>
                <input type="submit" value="Submit">
              </form> 
             
              
        </div>
        <div class="col-4">
            <form class="add_your_class"  action="{% url 'state:state_home' %}" >
                <input  id="search" name="search"type="search" name="search"> 
                <button  type="submit"> Search State</button>
            </form>
            
         </div>
        </div>
       
         
        <div class="col-12">
            <h3 class="text-center alert-primary alert">Filter Record Like This
                
            </h3>
            <h4><form class="add_your_class"  action="{% url 'state:state_home' %}" >
              
                <select name="country_search"  id="country_search">
                    {% for entry in countries %}
                        <option value="{{ entry.id }}">{{ entry.name }}</option>
                    {% endfor %}
                </select>
                <button  type="submit"> Search Country</button>
            </form></h4>
            {% if states %}
                  <table class="table table-hover">
                      <thead>
                          <tr>
                            <th scope="col">#ID.</th>
                            <th scope="col">COUNTRY</th>
                            <th scope="col">NAME</th>
                            <th scope="col">CODE</th>
                            <th scope="col">CREATED_AT</th>
                           
                          </tr>
                      </thead>
                      <tbody>
                        {% for data in states %}
                          <tr>
                              <td>{{ data.id }}</td>
                              <td>{{ data.country.name}}</td>
                              <td>{{ data.name }}</td>
                              <td>{{ data.code }}</td>
                              <td>{{ data.created_at }}</td>
                              
                             
                              <td>  <a href="{% url 'state:delete_state' data.id %}" class="btn btn-sm btn-info">Delete</a></td>
                              <td>  <a href="{% url 'state:edit_state_details' data.id %}" class="btn btn-sm btn-info">Edit</a></td>
                              <td>  <a href="{% url 'state:state_detail' data.id %}" class="btn btn-sm btn-info">Details</a></td>



                             

                          </tr>
                {% endfor %}
                      </tbody>

                  </table>
            {% else %}
                <h4 class="alert alert-danger text-center">No Records</h4>

            {% endif %}
        </div>
    </div>
    </div>
{% endblock content %}