city/urls.py
from django.contrib import admin
from django.urls import path
from .views import CityPageView,CityDeltailView,CityEditView,CityDeleteView


app_name='city'
urlpatterns = [
    path('city_home/', CityPageView.as_view(),name='city_home'),
    path('city_detail/<int:id>/',CityDeltailView.as_view(), name='city_detail'),
    path('edit_city_details/<int:id>/',CityEditView.as_view(), name='edit_city_details'),
    path('delete_city/<int:id>/', CityDeleteView.as_view(), name='delete_city'),


]

globe/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import HomeView
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',HomeView,name='home'),
    path(r'country/',include('country.urls'), name='country'),
    path(r'state/',include('state.urls'), name='state'),
    path(r'city/',include('city.urls'), name='city'),
    path(r'users/',include('users.urls'), name='users'),
    path(r'backendapp/',include('backendApp.urls'), name='backendapp'),
   
]

city/models.py
from django.db import models
from state.models import State
from django.contrib.auth.models import User

class City(models.Model):
    state = models.ForeignKey(State,on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    code = models.CharField(max_length=20)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(blank=True, null=True)
    is_deleted = models.BooleanField(default=False)
    created_by = models.ForeignKey(User,related_name='city_created_by',on_delete=models.CASCADE)
    updated_by = models.ForeignKey(User,related_name='city_updated_by',on_delete=models.CASCADE,blank=True,null=True)

city/views.py
from django.shortcuts import redirect, render,HttpResponseRedirect
from django.views import View
from state.models import State
from country.models import Country
from .models import City
from django.contrib import messages
from django.shortcuts import get_object_or_404
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required



def class_view_decorator(function_decorator):
    """Convert a function based decorator into a class based decorator usable
    on class based Views.

    Can't subclass the `View` as it breaks inheritance (super in particular),
    so we monkey-patch instead.
    """

    def simple_decorator(View):
        View.dispatch = method_decorator(function_decorator)(View.dispatch)
        return View

    return simple_decorator

    
@class_view_decorator(login_required) 
class CityPageView(View):
    def get(self,request):
        states = State.objects.filter(is_deleted=False)
        countries = Country.objects.filter(is_deleted=False)
        query = self.request.GET.get('search')
        state_serach = self.request.GET.get('state_search')
        country_search = self.request.GET.get('country_search')
        print(country_search)
        print(state_serach,"fjkjnfgn")
        if query:
             cities = City.objects.filter(name__icontains=query,is_deleted=False)
             print(cities)
        elif state_serach:
            cities = City.objects.filter(state__id__icontains=state_serach,is_deleted=False)
        elif country_search:

            cities = City.objects.filter(state__country__id__icontains=country_search,is_deleted=False)
           
        else:     
             cities = City.objects.filter(is_deleted=False)
        return render(request,'city/home.html',locals())
    def post(self,request):
            city_name = request.POST.get('name')
            city_code = request.POST.get('code')
            selected_state = (request.POST.get('state_id'))
          
            state_name  = State.objects.get(id=selected_state)
            print(state_name,"fddfsdbhdjbvjdf")
            data=City(name=city_name,code=city_code,state=state_name)
            print(data,"get")
            try:
                if state_name and city_name and city_code:
                    data.save()
                    messages.success(request, 'Created!!')
                else:
                    messages.warning(request, 'enter name ,code and country name!!!')

            except:
                messages.warning(request, 'Alreday exits')
            return redirect('city:city_home')


@class_view_decorator(login_required) 
class CityDeltailView(View):
    def get(self,request,id):
        city_detail = City.objects.get(pk=id)
        print(city_detail,"hi")
        return render(request,'city/details.html',{'city_detail':city_detail})


@class_view_decorator(login_required)         
class CityEditView(View):
    def get(self,request,id):
        city_detail = City.objects.get(pk=id)
        print(city_detail,"hi")
        return render(request,'city/edit.html',{'city_detail':city_detail})
    def post(self,request,id):
        city_name = request.POST.get('name')
        city_code = request.POST.get('code')
        city_detail = City.objects.get(pk=id)
        city_detail.name=city_name
        city_detail.code=city_code
        city_detail.save()
        return redirect('city:city_home')


@class_view_decorator(login_required)         
class CityDeleteView(View):
    def get(self,request,id):
        city_detail = City.objects.get(pk=id)
        print(city_detail,"hi")
        city_detail.is_deleted=True
        city_detail.save()
        messages.warning(request, 'Successfully Deleted')
        return redirect('city:city_home')        

templates/city/details.html
{% extends "base.html" %}

{% block content %}
<div class="row">
    <div class="col-sm-8">
        <h3 class="text-center alert-primary alert">Filter Record Like This</h3>

        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">#ID.</th>
                    <th scope="col">COUNTRY</th>
                    <th scope="col">STATE</th>
                    <th scope="col">Name</th>
                    <th scope="col">CODE</th>
                    <th scope="col">CREATED_AT</th>
                    <th scope="col">UPDATED_AT</th>

                </tr>
            </thead>
            <tbody>
               
                <tr>
                    <td>{{ city_detail.id }}</td>
                    <td>{{ city_detail.state.country.name }}</td>
                    <td>{{ city_detail.state.name }}</td>
                    <td>{{ city_detail.name }}</td>
                    <td>{{ city_detail.code }}</td>
                    <td>{{ city_detail.created_at }}</td>
                    <td>{{ city_detail.updated_at }}</td>
                </tr>
               
            </tbody>
        </table>

    </div>
</div>
{% endblock content %}

templates/city/edit.html
{% extends 'base.html' %}

{% block content %}
    <div class="row">
        <div class="col-md-6">
            <h4 class="text-center alert alert-primary">Country detail Update Here</h4>
            <form action="" method="post">
                {% csrf_token %}
                <label for="name">Name</label><br>
                <input type="text" id="name" name="name" value="{{ city_detail.name }}"><br>
                <label for="code">Code</label><br>
                <input type="text" id="code" name="code" value="{{ city_detail.code }}"><br><br>
                <input type="submit" value="Submit">
              </form> 
        </div>
    </div>
{% endblock %}

templates/city/home.html
{% extends "base.html" %} 

{% block content %}
    <div class="row">
        <div class="col-8">
            <h4 class="text-center alert alert-primary">Add new City</h4>
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-success alert-dismissible fade show" role="alert">
                        {{ message }}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                {% endfor %}
            {% endif %}
            <form action="" method="post">
                {% csrf_token %}
                <label for="name">Name</label><br>
                <input type="text" id="name" name="name" value="{{ states.name }}" required><br>
                <label for="code">Code</label><br>
                <input type="text" id="code" name="code" value="{{ states.code }}" required><br><br>
               
                <!-- <input type="text" id="item_id" name="item_id" value="{{ data.country }}"><br><br> -->
                <select name="state_id"  id="state_id">
                    {% for entry in states %}
                        <option value="{{ entry.id }}">{{ entry.name }}</option>
                    {% endfor %}
                </select>
                
                <input type="submit" value="Submit">
              </form> 
             
              
        </div>
        <div class="col-4">
            <form class="add_your_class"  action="{% url 'city:city_home' %}" >
                <input  id="search" name="search"type="search" name="search"> 
                <button  type="submit"> Search City</button>
            </form>
            
         </div>
         
        </div>
       
         
        <div class="col-12">
            <h3 class="text-center alert-primary alert">Filter Record Like This
            </h3>
            <h4><form class="add_your_class"  action="{% url 'city:city_home' %}" >
               
                <select name="state_search"  id="state_search">
                    {% for entry in states %}
                        <option value="{{ entry.id }}">{{ entry.name }}</option>
                    {% endfor %}
                </select>
                <button  type="submit"> Search State</button>
            </form>
        </h4>
        <h4><form class="add_your_class"  action="{% url 'city:city_home' %}" >
          
            <select name="country_search"  id="country_search">
                {% for entry in countries %}
                    <option value="{{ entry.id }}">{{ entry.name }}</option>
                {% endfor %}
            </select>
            <button  type="submit"> Search Country</button>
        </form>
    </h4>
            {% if cities %}
                  <table class="table table-hover">
                      <thead>
                          <tr>
                            <th scope="col">#ID.</th>
                            <th scope="col">COUNTRY</th>
                            <th scope="col">STATE</th>
                            <th scope="col">CITY NAME</th>
                            <th scope="col">CITY CODE</th>
                            <th scope="col">CREATED_AT</th>
                           
                          </tr>
                      </thead>
                      <tbody>
                        {% for data in cities %}
                          <tr>
                              <td>{{ data.id }}</td>
                              <td>{{ data.state.country.name}}</td>
                              <td>{{ data.state.name}}</td>
                              <td>{{ data.name }}</td>
                              <td>{{ data.code }}</td>
                              <td>{{ data.created_at }}</td>
                              <td>  <a href="{% url 'city:delete_city' data.id %}" class="btn btn-sm btn-info">Delete</a></td>
                              <td>  <a href="{% url 'city:edit_city_details' data.id %}" class="btn btn-sm btn-info">Edit</a></td>
                              <td>  <a href="{% url 'city:city_detail' data.id %}" class="btn btn-sm btn-info">Details</a></td>



                             

                          </tr>
                {% endfor %}
                      </tbody>

                  </table>
            {% else %}
                <h4 class="alert alert-danger text-center">No Records</h4>

            {% endif %}
        </div>
    </div>
    </div>
{% endblock content %}