city/urls.py
from django.contrib import admin
from django.urls import path
from .views import CityPageView,CityDeltailView,CityEditView,CityDeleteView


app_name='city'
urlpatterns = [
    path('city_home/', CityPageView.as_view(),name='city_home'),
    path('city_detail/<int:id>/',CityDeltailView.as_view(), name='city_detail'),
    path('edit_city_details/<int:id>/',CityEditView.as_view(), name='edit_city_details'),
    path('delete_city/<int:id>/', CityDeleteView.as_view(), name='delete_city'),


]

country/urls.py
from django.contrib import admin
from django.urls import path
from .views import HomePageView,DeltailView,EditView,DeleteView


app_name='country'
urlpatterns = [
    path('country_home/', HomePageView.as_view(),name='country_home'),
    path('detail/<int:id>/',DeltailView.as_view(), name='detail'),
    path('edit_detail/<int:id>/',EditView.as_view(), name='edit_detail'),
    path('delete_country/<int:id>/', DeleteView.as_view(), name='delete_country')
]

globe/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import HomeView
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',HomeView,name='home'),
    path(r'country/',include('country.urls'), name='country'),
    path(r'state/',include('state.urls'), name='state'),
    path(r'city/',include('city.urls'), name='city'),
    path(r'users/',include('users.urls'), name='users'),
    path(r'backendapp/',include('backendApp.urls'), name='backendapp'),
   
]

state/urls.py
from django.contrib import admin
from django.urls import path
from .views import StatePageView,StateDeleteView,StateEditView,StateDeltailView

app_name='state'

urlpatterns = [
    path('state_home/', StatePageView.as_view(),name='state_home'),
    path('delete_state/<int:id>/', StateDeleteView.as_view(), name='delete_state'),
    path('edit_state_details/<int:id>/',StateEditView.as_view(), name='edit_state_details'),
    path('state_detail/<int:id>/',StateDeltailView.as_view(), name='state_detail'),
]
# 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

users/urls.py
from django.contrib import admin
from django.urls import path
from .views import SignUpView,LoginView,LogoutView

app_name='users'
urlpatterns = [
    path('', SignUpView.as_view(),name='signup'),
    path('login/', LoginView.as_view(),name='login'),
    path('logout/',LogoutView.as_view(),name='logout')
   
]

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Class Based Django Application</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
    integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous" />
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
    integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
    integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
    crossorigin="anonymous"></script>
</head>

<body>
  <div class="container-fluid">
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
      
      {% if user.is_authenticated %}
      <a class="navbar-brand" href="{% url 'home' %}">Home</a>
      <a class="navbar-brand" href="{% url 'users:logout' %}">Logout</a>

      <a class="navbar-brand" href="{% url 'country:country_home' %}">Country</a>
      <a class="navbar-brand" href="{% url 'city:city_home' %}">City</a>

      <a class="navbar-brand" href="{% url 'state:state_home' %}">State</a>
      
      {% else %}
      <a class="navbar-brand" href="{% url 'users:login' %}">Login</a>
      {% endif %}
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>


    </nav>
    <div class="container mt-4">

      {% block content %}{% endblock content %}
    </div>
  </div>
</body>

</html>